<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Potfólio | GSFZamai</title>

    <link rel="stylesheet" href="./assets/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <form class="row g-3" action="cadastrar.php" method="post">
            <div class="col-md-12">
                <label for="titulo">Título do Projeto</label>
                <input class="form-control" type="text" name="titulo" placeholder="Título do Projeto" aria-label="default input example">        
            </div>

            <div class="col-md-12">
                <label for="imagem">Título Imagem do Projeto</label>
                <input class="form-control" type="text" name="imagem" placeholder="Título do Projeto" aria-label="default input example">        
            </div>

            <div class="col-md-6">
                <label for="github">Link Repositório GitHub</label>
                <input class="form-control" type="text" name="github" placeholder="https://www.github.com/gsfzamai/REPONAME" aria-label="default input example">        
            </div>

            <div class="col-md-6">
                <label for="link">Link Visualização</label>
                <input class="form-control" type="text" name="link" placeholder="https://www.seusite.com.br" aria-label="default input example">        
            </div>

            <div class="col-md-12">
                <label for="descricao">Descrição do Projeto</label>
                <textarea class="form-control" type="text" name="descricao" placeholder="https://www.github.com/gsfzamai/REPONAME" aria-label="default input example">        
                </textarea>
            </div>

            <button class="btn btn-success" type="submit">Cadastrar</button>
        </form>
    
    </div>
</body>
</html>